### ISSUE TITLE
Implement DatasetManagerContext and useDatasetManager

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#101]
### Context
As with the existing refine.bio, we want to be able to manage users' datasets when they use the application.

### Problem or idea
Using the context API, we'll create a dataset manager `DatasetManagerContext` which manages a user's dataset, keeps it in sync with the API, and handles the "Download Now" requests for one-off experiments. We'll also implement a hook named `useDatasetManager` for this context.

The general strategy should be to have a single context that;
- manages a user's dataset and keeps it in sync with the API
- keeps track a user's previous dataset ID by storing it in the local storage. Any data associated with the ID must be re-fetched from the API when the user returns (*unless the user clears cache or uses a different web browser/device to access our application).
- Queues changes made to an existing dataset

Each exposed method of this manager should correspond to the behavior of the application and indirectly communicates with the API using the [refinebio-js](https://github.com/AlexsLemonade/refinebio-js) helper.

**NOTE:** Multiple datasets may be supported in the future, but on the client side, only one dataset is active at a time. For instance, we can manage multiple datasets by storing `activeDatasetId` (currently selected dataset ID) and `datasetIds` (a collection of objects, each containing a dataset ID and its corresponding dataset nickname) in the local storage.

The implementation details and pseudocode is as follows:
#### <ins>Localstorage</ins>
`activeDatasetId`: a currently selected dataset UUID
`setActiveDatasetId`: an async method for setting `activeDatasetId`

`datasetIdHistory`:  a collection of history of user-created dataset ids
`setDatasetIdHistory`: an async method for adding a user-created dataset id to `datasetIdHistory`

`processingDatasetIds`:  a collection of dataset ids currently being processed  
`setProcessingDatasetIds`: an async method for adding/removing `processingDatasetIds`

#### <ins>Hook's Internal State</ins>
`currentDataset`: an instance of the public interface object returned by the helper 
`setCurrentDataset`: an async method for updating `currentDataset` to the latest instance

`processingDatasets`: a collection of the latest API response for datasets currently being processed 
`setProcessingDatasets`: an async method for refreshing `processingDatasets` to the latest API respons

#### &#10074; Functions

**Return Value:**`Dataset` 
An instance of the public Interface of the helper which will be stored in `currentDataset`, and it includes the following methods:
- `addExperiment(experimentAccession)`
- `removeExperiment(experimentAccession)`
- `addSample (experimentAccession, sampleAccession)` 
- `removeSample (experimentAccession, sampleAccession)`
- `emptyData()`
- `get(datasetId, details)`
- `getData()`
- `getOption(option)`
- `setOption(option, value)`
- `save()`
- `setEmail(email)`

(Parameters marked with * are required)

#### <ins>Internal Methods</ins>
They are called internally by other sibling methods in the manager.

**Dataset:**

`getDataset(id* = datasetId, details = boolean) return Dataset`
- fetches the latest state of the dataset with the given `id` via the helper
- returns `Dataset`

When the optional parameter `details` (false by default) is set to true, additional fields about the experiment in the dataset will be included in the returned object.

`getCurrentDataset() return Dataset`
- if there is no `currentDatasetId`:
   - calls `createDataset` to creates a new dataset 
- otherwise: 
  - calls `getDataset`
  - returns `Dataset`

`createDataset(setCurrent = boolean) return Dataset`
- create a new dataset via the helper 
- calls `setDatasetIdHistory` to save the newly created id 
- if the optional parameter `setCurrent` is true (by default):
   - calls `setCurrentDatasetId` 
- returns `Dataset`

`clearDataset() return Dataset`
- calls the helper's `emptyData` to empty the `data` object in the dataset
- returns `Dataset`

#### <ins>Common Methods</ins>
These methods are primarily called in the UI and each one corresponds to a specific application behavior.

**Experiment:**

`getTotalExperiments() return Integer`
 - returns the total length of the experiments, otherwise 0.

`hasExperiment(id*= experimentAccessionCode) return Boolean`
- returns true if the given `id` is present in the dataset, otherwise false.

`addExperiment(id* = experimentAccessionCode) return void`
- if there is no dataset: 
  - calls `createDataset`  to creates a new dataset 
- otherwise:
  - calls the helper's `addExperiment` 
  - calls the helper's `save` to save the new state

`removeExperiment(id* = experimentAccessionCode) return void`
- calls the helper's `removeExperiment`
  - calls the helper's `save` to save the new state

**Sample:**

`getTotalSamples(data* = dataset.data) return Integer` 
- returns the total length of the samples in the dataset, otherwise 0.

`hasSample(id1* = experimentAccession, id2* = SampleAccession) returns Boolean`
- returns true if the sample with `id2` is present in the experiment with `id1`, otherwise false.

`addSample(id1* = experimentAccessionCode, id2* = sampleAccessionCode) return void`
- calls the helper's `addSample`
- calls the helper's `save` to save the new state

`removeSample(id1* = experimentAccessionCode, id2* = sampleAccessionCode) return void`
- calls the helper's `removeSample`
- calls the helper's `save` to save the new state

**Download:**

`downloadExperiment(id* = experimentAccession, options* = downloadOptions) return Dataset`
- creates a new dataset via the helper
- calls the helper's `addExperiment`
- calls the helper's `setEmail`
- calls `processDataset`
- calls `setDownloads` to store this newly created dataset id
- returns `Dataset`

`getDownloadOption(option) -> Value`
- calls helper's `getOption` with the given `option`
- returns the value of the option

`setDownloadOption(option*, value*) return Object`
- calls helper's `setOption` with the given `option` and its `value`
- returns the key and value of the updated option

`processDataset(datasetId) return Dataset`
- if no token: 
  - create a new token via the helper 
  - sets the token and stores in the local storage
- calls the helper's `setOption` to sets the `start` to true 
- calls the helper's `save` to save the new state
- returns `Dataset`

**Example:**
```js
const addExperiment = async (experimentAccessionCode) => {
    if (!currentDatasetId) {
         await createDataset()
    }

    currentDataset.addExperiment(experimentAccessionCode)
    const dataset = await currentDataset.save()
    updateCurrentDataset(dataset)
}
```
--- continue to improve based on the feedback as necessary ---

**Comment by nozomione** [comment]
This feature branch will be created based on the latest [`dev`](https://github.com/AlexsLemonade/refinebio-web/pull/23), thank you!

**Comment by nozomione** [comment]
🗒️ The new epic https://github.com/AlexsLemonade/refinebio-web/issues/174 was created to divide the scope of this issue into smaller parts, thus closing it.
