### ISSUE TITLE
Deploy Script to generate sitemap.xml

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#123]
### Context

We need to generate sitemaps on deploy. 

### Problem or idea

We essentially want to have [this script](https://github.com/AlexsLemonade/refinebio-frontend/blob/dev/sitemap.js) from the older version of refinebio-frontend but we should use refinebio-js for fetching the results.

### Solution or next step

- [x] Refactor the current version of the script (Done in [#125](https://github.com/AlexsLemonade/refinebio-web/pull/125))
- [ ]  Set up the domains for `staging` and `prod` (closes [#7](https://github.com/AlexsLemonade/refinebio-web/issues/7))
- [ ]  Set up the environments in the project code and Vercecl
- [ ]  Add the script to the deploy process of refinebio-web
- [ ] Test the script to ensure that it works as expected

Note: we should remove this from the deploy process on staging because this adds a considerable amount of time to the build step (~5m). We should first test this on staging and then in a future issue / PR remove it and only have it run on production deploys.

**Comment by nozomione** [comment]
**NOTE:** This feature branch will be created based on the latest [PR #119](https://github.com/AlexsLemonade/refinebio-web/pull/119) (114 - Clean up Sample Details Page Code).
