### ISSUE TITLE
Migrate the localStorage data

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/refinebio-web#129]
### Context
Currently, we use the localStorage web API to store user information (e.g., a user-defined dataset ID saved in "My Dataset" page). Those data must still be preserved when we migrate the source code from [`refinebio-frontend`](https://github.com/AlexsLemonade/refinebio-frontend/) to [`refinebio-web`](https://github.com/AlexsLemonade/refinebio-web).

### Problem or idea
We should create a helper method to handle the migration of users' data stored in localStorage.

The following key will be migrated:
<table>
  <thead>
    <tr>
      <th>Old Key</th>
      <th>New Key</th>
      <th>Default Value</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>dataSetId</code></td>
      <td><code>datasetId</code></td>
      <td><code>null</code></td>
      <td>A dataset ID which is a UUID string.</td>
    </tr>
  </tbody>
</table>

Although `refinebio-frontend` and `refinebio-web` use different key names, the following keys won't be included in the migration support:

<table>
  <thead>
    <tr>
      <th>Old Key</th>
      <th>New Key</th>
      <th>Default Value</th>
      <th>Description</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>firstTimeVisitor</code></td>
      <td><code>visited-before</code></td>
      <td><code>false</code></td>
      <td>Checks whether a user has previously visited the site. If not, the banner should be displayed on the search results page. Otherwise, the banner should be hidden and this key value should be <code>true</code>.</td>
     <td>No side effect.</td>
    </tr>
     <tr>
      <td>
          <ul>
             <li><code>dataset-ACCESSION_CODE</code><br/>(an object)</li>        
              <li><code>shown-procesing-modals</code><br/>(an array)</li>
         </ul>
     </td>
      <td><code>processing-experiments</code><br/>(an array)</td>
      <td><code>[]</code></td>
      <td>Renders a temporary UI while an one-off experiment dataset is being processed.</td>
     <td>It's unlikely that users will initiate an one-off experiment process concurrently with our site swap. And if they do, there won't be any serious side effects since they'll receive an email notification when the download file is available.</td>
    </tr>
  </tbody>
</table>

**NOTE:** We should discontinue the migration support and clean up the helper from the codebase after a certain period of time (e.g., 12 months) has passed since the site swap.

### Solution or next step
(*due to frequent PR merges, the most recent PR's feature branch will be used as the base branch to reduce merge conflicts)

- Implement the helper to support necessary old localStorage keys in `refinebio-frontend` and transfer their values to the new corresponding localStorage keys in `refinebio-web`

**Comment by davidsmejia** [comment]
Before we start on creating a manager for this purpose please start by creating a table with the following columns that we can track on this issue. 

- `Old Key`:  The key used in refinebio-frontend. This may be blank.
- `New Key`:  The key that is used on refinebio-web
- `Transformation`:  Describe the change that would be required to migrate the old value to the new value if required.

I don't think that a "manager" would be necessary here. We really only need to have a function execute at the top of the application and migrate the keys and values over once. Lets start by mapping out what we would need to change and then decide on where would be best to implement the code that actually moves it over.
