### ISSUE TITLE
Search Page Text Search + Results (Without Filtering)

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#27]
### Context

The search page should be able to list result from the `/search` endpoint. The results should be queried before page load and rendered as a list. After the page has loaded we should hand off requesting the new data to the front end.

Filtering should not be addressed in this PR. Pagination should be addressed. You should be able to enter text into the search box and submit it and have the page load the results.

### Problem or idea

N/A

### Solution or next step

Implement the text search on the search page. Render the list of results. Pagination should be supported in this PR.

**Comment by nozomione** [comment]
Completed in https://github.com/AlexsLemonade/refinebio-web/pull/126.
