### ISSUE TITLE
Search Page Filtering

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#28]
### Context

After the search page text search has been implemented we should move forward with implementing the rendering and functionality of filters for search. They should render from the search results and update after each interaction.

### Solution or next step

This pr should include the dynamic rendering of the filter component. This should come from the facets attribute in the search endpoint response.

**Comment by nozomione** [comment]
Completed in https://github.com/AlexsLemonade/refinebio-web/pull/126.
