### ISSUE TITLE
QA: Anchor View samples button to samples section on experiment page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-web#280]
### Context
When I click on the `View Samples` button, it takes me to the top of the experiment page.

### Problem or idea
It should link to the samples section on the experiment page instead

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by nozomione** [comment]
Hello @dvenprasad, This behavior is the same as the current refine.bio. The data in the samples table needs to be fetched first when the experiment page loads. For this, it displays a loading spinner animation when a user enters the page.

Do you want to add an auto-scroll-down to the samples table section **after** the data has finished loading? Please let me know!

**Comment by nozomione** [comment]
Yes, it typically doesn't take more than a few seconds! The page renders a loading spinner while fetching the submitter supplied information and the samples table section. The data in the samples table is loaded using a separate hook. The page will render the table UI once the data is loaded (with populated HTML element's properties with that fetched data) and auto-scroll it to the top of the page.
