### ISSUE TITLE
QA:Regenerate button on Download page doesn't seem to do anything

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-web#281]
### Context
When I change (or not change) download options and click on `Regenerate Dataset, there is not feedback

### Problem or idea
Not sure if this isn't linked yet, but ideally it should redirect me to a new processing dataset page.

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by nozomione** [comment]
Hello @dvenprasad, I've noticed that currently the "Regenerate Dataset" button doesn't work in`production`, so I've fixed it in `refinebio-web`. Could you please test it again? Thank you!

refine.bio Production:  https://www.refine.bio/dataset/3c7e16ee-e882-4cd3-912d-a65d11e85c62
refinebio-web Staging: https://staging.web.refine.bio/dataset/3c7e16ee-e882-4cd3-912d-a65d11e85c62
