### ISSUE TITLE
Remove Page and Size query parameter

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#293]
### Context

Before we release `refinebio-web` as the new default client implementation we should remove the customized query parameters.

The only exception at this time is `filter_order` which will be removed when the API has been updated to account for this behavior.

### Solution or next step

Remove the FE only query params from the search page so that there is 1:1 parity with what we pass to the API.

- remove `p`
- remove `size`
- surface `limit` and `offset` along with all other query parameters

**Comment by nozomione** [comment]
> Remove the FE only query params from the search page so that there is 1:1 parity with what we pass to the API.
> 
>    - remove `p`
> 
>   -  remove `size`
> 
>    - surface `limit` and `offset` along with all other query parameters

@davidsmejia  I am using them to calculate pagination etc. Let's keep the implementation as is. 

As mentioned earlier (one of the reference https://github.com/AlexsLemonade/refinebio-web/pull/126#issuecomment-1644586563), it's standard practice to use `p` (or `page` etc) in FE to create user-friendly URLs for web apps (e.g.,  e-commerce sites (like amazon), news site (like NYT)). As far as I know, I can't find any web apps that use `limit` and `offset`(although they are commonly used in BE APIs). 

Please let me know your thought on this 💭
