### ISSUE TITLE
Implement About Page

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#30]
### Context

Add the necessary components and implement them on the about page.

**Comment by nozomione** [comment]
@davidsmejia This PR will be created based on the branch ` nozomione/26-create-global-components-for-app-structure`, for it's a dependent of the issue [#26](https://app.zenhub.com/workspaces/engineering-5c92300a9d1bd30b8d3101f2/issues/alexslemonade/refinebio-web/31), thank you!
