### ISSUE TITLE
GA implementation review

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#338]
### Context

I was reviewing the open GA issues and wanted to comment on more than one of them so I am opening this issue to ensure that these notes are addressed in each of them. Note this is not the entire review and each PR may have their own changes or explanations requested.

### Problem or idea

We should ensure that the current GA PRs adhere to the following:

- No static strings or values are defined outside of the function.
- No data is pre-formatted before passing to a `gtag.specificTrackingEventName` function.
- Every tracked metric will have a unique function. Data will be unformatted and be mutated in the function.

If two or more functions are very similar but do not track the same event, write functionality that can be shared between them but distinguish them by their function name.

### Solution or next step

- Ensure all open PRs related to GA adhere to the above principles

**Comment by davidsmejia** [comment]
Lets start with the first 5 start with the oldest and I will review those and we can move forward from there.

**Comment by nozomione** [comment]
**Epic:** [GA4 Integration](https://github.com/AlexsLemonade/refinebio-web/issues/302)

This issue is to revise the following PRs: 

3. - [ ] https://github.com/AlexsLemonade/refinebio-web/pull/321 (Gtag custom event script which is used in PRs below)
     - [x] https://github.com/AlexsLemonade/refinebio-web/pull/322 
     - [x] https://github.com/AlexsLemonade/refinebio-web/pull/323
     - [x] https://github.com/AlexsLemonade/refinebio-web/pull/324
     - [x] https://github.com/AlexsLemonade/refinebio-web/pull/325
     - [ ] https://github.com/AlexsLemonade/refinebio-web/pull/326
     - [ ] https://github.com/AlexsLemonade/refinebio-web/pull/327

**Comment by nozomione** [comment]
Completed the items listed.
