### ISSUE TITLE
Samples Table: Implementation notes and more

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-web#34]
### Context

@nozomione and I met to discuss samples table (ref https://github.com/AlexsLemonade/refinebio-admin/issues/87)

### Problem or idea
Notes from the meeting:
- Design notes on minor characteristics of the table:
-  Bordered rows and columns
-  Striped rows
-  Sortable columns  with 3 states: Ascending, Descending and Default (or reset)
- Resizable columns
- Highlight row on hover- Highlight color: #d4e1f1
- Filtering as it is on current implementation of refine.bio
- Make the first 3 columns fixed - Add/Remove, Accession ID, Title

- Redesign how `Expand Table` works
  - Expand table shows a full-width and "full screen" version of the table
  - Try adding transition when the table expands and collapses

Samples table Annotated:
(also available on refinebio-master > Experiment page on Figma
![sample-table-annotations](https://user-images.githubusercontent.com/15315514/202289022-983a8e28-3f9c-4c66-9aca-9654141589f9.png)

**Comment by nozomione** [comment]
- UI implementation was completed in [#41](https://github.com/AlexsLemonade/refinebio-web/pull/41#issuecomment-1594851368)
- API integration for the [samples](https://api.refine.bio/v1/#tag/samples) endpoint was completed in [#131](https://github.com/AlexsLemonade/refinebio-web/pull/131)
