### ISSUE TITLE
Implement Samples Table

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#36]
### Context

Implement the Samples Table based on discussion from: https://github.com/AlexsLemonade/refinebio-web/issues/34

**Comment by nozomione** [comment]
**NOTE:** This feature branch will;
-  be created based on the `nozomione/35-implement-compendia-page` branch
-  include(pull) the latest update of the `nozomione/37-add-responsive-to-search-result-page` branch

This is a dependent of [(PR) 35 - Implement Compendia Page ](https://github.com/AlexsLemonade/refinebio-web/pull/39) and [(PR) 37 - Add Responsive to Search Result Page](https://github.com/AlexsLemonade/refinebio-web/pull/38). Thank you!

**Comment by nozomione** [comment]
Completed in [#41](https://github.com/AlexsLemonade/refinebio-web/pull/41#issuecomment-1594851368).
