### ISSUE TITLE
Discussion: UI presentation when /dataset/id matches user's My Dataset ID 

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/refinebio-web#362]
### Context

Epic: #358

We'd like to discuss a few ideas regarding the UI presentation when `/dataset/id` matches a user's My Dataset ID.

Currently, when `/dataset/id` matches the user's My Dataset ID, the dataset page displays the shared dataset details without indicating that the user is viewing their own dataset, My Dataset, as 'shared'. This could make the `Move to Dataset` button action seem redundant.

I've added a quick ID check that disables this button when URL's `id` matches My Dataset ID. This was added during development for testing various dataset types on this page and can be easily removed as needed (please see https://github.com/AlexsLemonade/refinebio-web/pull/294#discussion_r1639032749 in Other Variable section's `isSameId`).

e.g. ) When My Dataset ID matches `id` in the URL:

![shared_dataset_with_my_dataset_id](https://github.com/user-attachments/assets/1f2e2b49-dcce-44f0-8081-f727944bf52c)

### Problem or idea
Here are a couple of options for handling this case:

1. Show a banner and disable `Move To Dataset`
   - Add a banner to the `/dataset` page to inform users they're viewing their own dataset
   - Continue disabling the `Move To Dataset` button to prevent users from performing the action (as shown in the screenshot)
2. Redirect the user to `/download`
   - Automatically redirect users to the `/download` page if they access `/dataset/id` where the `id` matches their My Dataset ID

### Solution or next step
We'd love to hear your feedback on these suggestions and any other ideas you might have. Your insights would be really valuable in refining the UI/UX. Thank you, Deepa! Tagging @dvenprasad and @davidsmejia for further discussion.

- [x] Get feedback from Deepa
- [ ] Include the chosen solution in a PR for #360

**Comment by dvenprasad** [comment]
I see. This is not a common scenario. We should redirect them to their cart in this case.

To clarify: let's say there are 2 datasets. When user has dataset 1 in cart and then clicks on share link for dataset 1 they are redirected to their cart. 

When the same user has dataset 2 in their cart and open the share link for dataset 1, they are shown the 'Shared Dataset' page. 

Is that correct?

**Comment by nozomione** [comment]
> I see. This is not a common scenario. We should redirect them to their cart in this case.
> 
> To clarify: let's say there are 2 datasets. When user has dataset 1 in cart and then clicks on share link for dataset 1 they are redirected to their cart.
> 

Yes, when a user visits the dataset page (e.g.,`dataset/1`) that matches their My Dataset ID (e.g.,`1`), that user will be redirected to the `download/` page, which is also accessible via the `My Dataset` button in the site nav.

> When the same user has dataset 2 in their cart and open the share link for dataset 1, they are shown the 'Shared Dataset' page.
> 
> Is that correct?

And yes, if a user visits the dataset page via a shared link (e.g., `dataset/1?ref=share`) where `id` isn’t their My Dataset ID (e.g., `2`), the dataset `1` will show up as "Shared Dataset" following normal flow 👍!

**Comment by nozomione** [comment]
@davidsmejia , I'll file a new issue for this once I receive the green light from @dvenprasad!

**Comment by dvenprasad** [comment]
Yep, redirecting it to the cart `/download` sounds good to me.
