### ISSUE TITLE
Implement Download Pages

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#40]
### Context

We have designs for how the download pages should look. Let's implement them.

### Solution or next step

Implement the download pages.

**Comment by nozomione** [comment]
Hello @davidsmejia, let's split this issue into more smaller and digestible features to make it easier to review.

**Feature 1:** My Dataset Process View (4 screen types)
**Feature 2:** My Dataset Advanced Option
 ( *Without modals - there is a tab menu for "Species View" and "Experiment View" that has modals for Samples table)

**NOTE:** As discussed previously, the modals(5 types) for the download pages, they will be handled separatly and will not be included in this issue.

Please review the [mockup](https://www.figma.com/file/2cxEjUKA4ACTjDYSnDEWpR/refinebio-master?node-id=116%3A5475&t=UlngP7dm6o2XmKsC-0) and let me know if any questions/suggestions, thank you!
