### ISSUE TITLE
Set domain for new frontend

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#7]
connect vercel project to beta.refinebio.bio and staging.beta.refine.bio

Steps in Vercel:
- [x] Create a new project for `refinebio-web` 
- [x] Define required environmental variables for our API and for the Sentry SDK(*values are temporarily unassigned) 
- [x] Add and configure the required (sub)domains

**Comment by nozomione** [comment]
@davidsmejia This ticket should be completed to properly set up the staging (`dev`) and production (`main`) environments in Vercel.  Currently the defaul Vercel domain is used as production (points to `main`).

Let's take a look at this ticket, again 🔍

**Comment by nozomione** [comment]
The following subdomains were created and added on Vercel by @davidsmejia (thank you), thus closing this issue 🎉 !
- Preview: [staging.web.refine.bio](http://staging.web.refine.bio/) (points to the `dev` branch)
- Production: [web.refine.bio](http://web.refine.bio/) (points to the `main` branch)
