### ISSUE TITLE
Implement Sample Details Page

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/refinebio-web#91]
### Context
**The type of Implementation:** New feature (non-breaking change which adds functionality)

The application displays the sample details page when a user clicks on each sample accession code in the samples table, and we need to implement it.

### Problem or idea
1. A user clicks one of the sample accession code in the samples table.
![image](https://user-images.githubusercontent.com/31800566/224181835-dca5845e-c991-4625-8a7c-6cde7d1f403a.png)
2. It directs the user to the corresponding sample details page that displays the 'Sample Details' and togglable 'Debug Information' sections. 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/31800566/228543049-e9b239eb-7759-4608-9b9a-ca402c204a11.png">
Based on the design, we'll create the sample details page. 

### Solution or next step
- Add a new route for the sample details page
- Use existing components or create a new one to build the sample details UI
- Create any sub-components or helpers as necessary

**Comment by nozomione** [comment]
This feature branch will be created based on the [PR #102](https://github.com/AlexsLemonade/refinebio-web/pull/102) branch, thank you!

**Comment by davidsmejia** [comment]
This page should not be implemented. Explanation here: https://github.com/AlexsLemonade/refinebio-web/pull/103#issuecomment-1500495709
