### ISSUE TITLE
Show Includes Publication(0) when experiments have no publication in result

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-web#99]
### Context
Came up while reviewing #96 

### Problem or idea
![Screenshot 2023-03-22 at 3 59 37 PM](https://user-images.githubusercontent.com/15315514/227025263-c73c906c-439e-498c-ac05-17e538f8c485.png)

When the experiments in the result set do not have any publications associated with them, the filter `Includes Publication` filter is active and users can choose to add that filter. 

For other filters, we remove the items that aren't in the result set. 

### Solution or next step

In this case, includes publication is its own facet, so we can show `Includes Publication (0)` and disable it. 

I'm also open to removing it as a filter when the count is 0. 

Tagging @davidsmejia @nozomione for thoughts

**Comment by nozomione** [comment]
> In this case, includes publication is its own facet, so we can show Includes Publication (0) and disable it.

@davidsmejia  Since I am working on these pages, this is a good time to implement @dvenprasad's suggestion 👍🏻 I can take care of this issue today. Please let me know!
